# Generated by Django 4.0.6 on 2022-07-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_List', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='complete',
        ),
    ]
